<?php

/**
 * ProcessWire 'Hello world' demonstration module
 *
 * Demonstrates the Module interface and how to add hooks.
 * 
 * See README file for further links regarding module development.
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2015 by Ryan Cramer 
 * This file licensed under Mozilla Public License v2.0 http://mozilla.org/MPL/2.0/
 * 
 * https://processwire.com
 *
 */

class yink_links extends WireData implements Module {
	

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'Help in generating urls', 

			'version' => 1,
			'summary' => 'Class that helps to generate urls',
			'href' => 'http://myhilarious.com',
			'singular' => true,
			'autoload' => true,
			'icon' => 'smile-o', 
			);
	}

	/**
	 * Initialize the module
	 *
	 * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
	 * when ProcessWire's API is ready. As a result, this is a good place to attach hooks. 
	 *
	 */
	public function init() {
	
	} 
	//from  site dirctory
	public static function get_current_url(){
		if (wire('config')->https) {
			return "https://$_SERVER[HTTP_HOST]".strtok($_SERVER["REQUEST_URI"],'?');
		} else {
		return "http://$_SERVER[HTTP_HOST]".strtok($_SERVER["REQUEST_URI"],'?');	
		}
		
			//	echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";  
			
		
	} 





	
}